# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e22289b4c5604ee08c2a075b15d38dbce4a71e0d0a710a486c0ba1842542cfd54500f23148dea54f60174f98a751882c95447b5c7658f5035e7ee0d7a3d770d9

test:
  secret_key_base: 3bd4e4f7fbb4196ff504e9463ae054daa3fbcee216279f79acbededd03afa0c9abbd6bc4a7e5c248ac849e68b70c3f354c9f37f78133cf27b059002a2b31a38d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
